package org.jboss.fuse.wsdl2rest.test.doclit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000243-redhat-1
 * 2018-09-11T13:01:08.483-04:00
 * Generated source version: 3.1.11.fuse-000243-redhat-1
 * 
 */
@WebService(targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", name = "Address")
@XmlSeeAlso({ObjectFactory.class})
public interface Address {

    @WebMethod
    @RequestWrapper(localName = "delAddress", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.DelAddress")
    @ResponseWrapper(localName = "delAddressResponse", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.DelAddressResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.jboss.fuse.wsdl2rest.test.doclit.Item delAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addAddress", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.AddAddress")
    @ResponseWrapper(localName = "addAddressResponse", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.AddAddressResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Integer addAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        org.jboss.fuse.wsdl2rest.test.doclit.Item arg0
    );

    @WebMethod
    @RequestWrapper(localName = "listAddresses", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.ListAddresses")
    @ResponseWrapper(localName = "listAddressesResponse", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.ListAddressesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String listAddresses();

    @WebMethod
    @RequestWrapper(localName = "updAddress", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.UpdAddress")
    @ResponseWrapper(localName = "updAddressResponse", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.UpdAddressResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Integer updAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        org.jboss.fuse.wsdl2rest.test.doclit.Item arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAddress", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.GetAddress")
    @ResponseWrapper(localName = "getAddressResponse", targetNamespace = "http://doclit.test.wsdl2rest.fuse.jboss.org/", className = "org.jboss.fuse.wsdl2rest.test.doclit.GetAddressResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.jboss.fuse.wsdl2rest.test.doclit.Item getAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );
}
